window.PILOT_QUESTIONS = [
  {
    "id": "RM-2024-A-001",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "1",
    "area": "Pediatría",
    "specialty": "Otorrinolaringología pediátrica",
    "topic": "Sinusitis",
    "subtopic": "Diagnóstico",
    "question": "Niño de 6 años, presenta hace 7 días rinorrea mucopurulenta, tos persistente que se intensifica al correr y cefalea. Antecedente: rinitis alérgica con corticoides intranasales en 3 episodios similares al año. Examen: T° 36.5 °C, FC 85 X´; secreción purulenta en rinofaringe posterior; resto no contributorio. ¿Cuál es el examen diagnóstico de elección?",
    "option_a": "Microbiología",
    "option_b": "Tomografía",
    "option_c": "Serología",
    "option_d": "Radiografía",
    "option_e": "",
    "official_answer": "D",
    "official_answer_text": "Radiografía",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.97,127.22,540.10,139.94",
    "source_pdf": "2024 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "dc3bd5da40436c820a1ddf9046bf185b5accb714d64c7e0203ba120ca77f376a",
    "content_sha256": "a41a8b09e593398448e3dd177c0eb0339844c3369c3db759924bfef079000c36",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "OBSERVADA_DESACTUALIZADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "Clave oficial del PDF: D, radiografía. Históricamente se usó la radiografía de senos paranasales para buscar opacificación, engrosamiento mucoso o niveles hidroaéreos. Sin embargo, esta pregunta queda observada: en la práctica pediátrica actual la sinusitis bacteriana aguda no complicada se diagnostica clínicamente y no se recomienda imagen rutinaria. Además, 7 días de síntomas sin inicio grave ni doble empeoramiento no bastan, por sí solos, para el criterio clásico de persistencia.",
    "why_not_a": "La microbiología no se obtiene de forma rutinaria. Un cultivo nasal o nasofaríngeo no identifica de manera fiable al germen sinusal; la aspiración del seno se reserva para situaciones seleccionadas.",
    "why_not_b": "La tomografía no es el examen rutinario de una sinusitis aguda no complicada; se reserva para sospecha de complicación orbitaria/intracraneal, enfermedad refractaria o planificación quirúrgica.",
    "why_not_c": "La serología no tiene utilidad para confirmar una sinusitis bacteriana aguda común.",
    "why_not_d": "",
    "why_not_e": "",
    "exam_pearl": "Sinusitis bacteriana pediátrica: pensar en persistencia ≥10 días sin mejoría, inicio grave o empeoramiento tras mejoría inicial. Caso no complicado = diagnóstico clínico, sin imagen rutinaria.",
    "update_alert": "Clave histórica desactualizada respecto de guías actuales; no usar radiografía rutinaria para confirmar sinusitis aguda no complicada.",
    "reference_notes": "La clave oficial D (radiografía) no es compatible con las recomendaciones pediátricas actuales para sinusitis aguda no complicada: el diagnóstico es clínico y no se recomienda imagen rutinaria. Además, 7 días de síntomas sin inicio grave ni empeoramiento no cumplen por sí solos el criterio clásico de persistencia ≥10 días para sinusitis bacteriana aguda.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "OBSERVADA_DESACTUALIZADA",
    "audit_current_assessment": "La clave oficial D (radiografía) no es compatible con las recomendaciones pediátricas actuales para sinusitis aguda no complicada: el diagnóstico es clínico y no se recomienda imagen rutinaria. Además, 7 días de síntomas sin inicio grave ni empeoramiento no cumplen por sí solos el criterio clásico de persistencia ≥10 días para sinusitis bacteriana aguda.",
    "audit_current_answer": "Ninguna de las alternativas: diagnóstico clínico; sin imagen rutinaria en caso no complicado.",
    "audit_app_behavior": "Conservar la clave oficial D para modo histórico, mostrar alerta visible y excluirla del puntaje de dominio/maestría por defecto.",
    "audit_source_urls": "https://publications.aap.org/pediatriccare/article/doi/10.1542/aap.ppcqr.396228/139/Sinusitis",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-A-002",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "2",
    "area": "Medicina Interna",
    "specialty": "Neumología",
    "topic": "EPOC",
    "subtopic": "Espirometría",
    "question": "Varón de 77 años, fumador, acude por presentar tos productiva crónica, astenia, disnea de esfuerzo y últimamente de reposo, anorexia y baja de peso. Se le realiza espirometría: VEF1/CVF < 70% (post broncodilatadores). ¿Cuál es el patrón?",
    "option_a": "Normal",
    "option_b": "Obstructivo",
    "option_c": "Restrictivo",
    "option_d": "Mixto",
    "option_e": "",
    "official_answer": "B",
    "official_answer_text": "Obstructivo",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "55.20,202.94,281.33,215.66",
    "source_pdf": "2024 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "dc3bd5da40436c820a1ddf9046bf185b5accb714d64c7e0203ba120ca77f376a",
    "content_sha256": "99c04fa07001fe0ac5d4c4a19d590544c25d323a246a281826998a97be9a60ac",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "Un VEF1/CVF posbroncodilatador <0,70 demuestra limitación persistente al flujo aéreo, es decir, un patrón obstructivo. En un adulto mayor fumador con clínica respiratoria crónica, este hallazgo es compatible con EPOC.",
    "why_not_a": "Un patrón normal no presenta una relación VEF1/CVF reducida por debajo del umbral diagnóstico.",
    "why_not_b": "",
    "why_not_c": "El patrón restrictivo se caracteriza principalmente por disminución de la capacidad vital y de los volúmenes pulmonares, con una relación VEF1/CVF normal o aumentada; la restricción se confirma con volúmenes pulmonares.",
    "why_not_d": "Un patrón mixto requiere datos de obstrucción y restricción. La relación baja demuestra obstrucción, pero con la información dada no se ha demostrado disminución de la capacidad pulmonar total.",
    "why_not_e": "",
    "exam_pearl": "EPOC: VEF1/CVF posbroncodilatador <0,70 = obstrucción persistente.",
    "update_alert": "",
    "reference_notes": "VEF1/CVF posbroncodilatador <0,70 corresponde a un patrón obstructivo y es el criterio espirométrico requerido para confirmar obstrucción persistente compatible con EPOC.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "VEF1/CVF posbroncodilatador <0,70 corresponde a un patrón obstructivo y es el criterio espirométrico requerido para confirmar obstrucción persistente compatible con EPOC.",
    "audit_current_answer": "B. Obstructivo",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://goldcopd.org/spirometry-quick-guide/",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-A-003",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "3",
    "area": "Medicina Interna",
    "specialty": "Endocrinología",
    "topic": "Cetoacidosis diabética",
    "subtopic": "Clasificación de severidad",
    "question": "Mujer de 46 años, acude por dolor abdominal, náusea y vómitos. Antecedentes: diabetes mellitus con tratamiento irregular. Examen: PA 90/60 mmHg, FC 100 X', FR 28 X', somnolienta. Laboratorio: glucosa 380 mg/dl; examen de orina: leucocituria y cuerpos cetónicos presentes, gasometría: pH 7.10, bicarbonato 14 mEq/l. ¿Cuál es el grado de severidad?",
    "option_a": "Severa",
    "option_b": "Moderada",
    "option_c": "Grave",
    "option_d": "Leve",
    "option_e": "",
    "official_answer": "B",
    "official_answer_text": "Moderada",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "55.20,278.81,281.33,291.41",
    "source_pdf": "2024 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "dc3bd5da40436c820a1ddf9046bf185b5accb714d64c7e0203ba120ca77f376a",
    "content_sha256": "b8c2d983f5cc65487a8e2843fc5d6477e3dbe0ce265cd08ccfc79643e06d1875",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "La paciente tiene cetoacidosis diabética y la magnitud de la acidosis es compatible con severidad moderada: pH 7,10 y bicarbonato 14 mEq/L. El compromiso del sensorio refuerza que no se trata de una forma leve.",
    "why_not_a": "La categoría severa se reserva para una acidosis más profunda y mayor compromiso clínico; con bicarbonato 14 mEq/L, la clasificación que mejor encaja es moderada.",
    "why_not_b": "",
    "why_not_c": "“Grave” no constituye una categoría distinta de “severa” en la clasificación estándar leve/moderada/severa; además, la alternativa oficial que corresponde a estos valores es moderada.",
    "why_not_d": "La CAD leve presenta una acidosis menos intensa; pH 7,10 y HCO3 14 mEq/L exceden el rango de una forma leve.",
    "why_not_e": "",
    "exam_pearl": "CAD: la severidad se clasifica por la magnitud de la acidosis (pH/bicarbonato) y el estado clínico, no por la glucosa aislada.",
    "update_alert": "",
    "reference_notes": "pH 7,10 y bicarbonato 14 mEq/L encajan en cetoacidosis diabética moderada; la somnolencia también es compatible con mayor compromiso clínico que una CAD leve.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "pH 7,10 y bicarbonato 14 mEq/L encajan en cetoacidosis diabética moderada; la somnolencia también es compatible con mayor compromiso clínico que una CAD leve.",
    "audit_current_answer": "B. Moderada",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://diabetesjournals.org/care/article-pdf/47/8/1257/780938/dci240032.pdf",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-A-004",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "4",
    "area": "Gineco-Obstetricia",
    "specialty": "Obstetricia",
    "topic": "Restricción del crecimiento fetal",
    "subtopic": "Conducta obstétrica",
    "question": "Primigesta de 38 semanas, acude por presentar disminución de movimientos fetales. Examen: PA 130/90 mmHg, FC 72 X'. Altura uterina 28 cm. SPP: LCI, LCF: 140 X'. Ecografía obstétrica: gestación única activa con ponderado fetal percentil 1 y perfil biofísico 6/10. ¿Cuál es la conducta a seguir?",
    "option_a": "Evolución espontánea de parto",
    "option_b": "Cesárea a las 40 semanas",
    "option_c": "Terminar la gestación",
    "option_d": "Control en una semana con doppler",
    "option_e": "",
    "official_answer": "C",
    "official_answer_text": "Terminar la gestación",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.97,341.93,540.10,354.53",
    "source_pdf": "2024 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "dc3bd5da40436c820a1ddf9046bf185b5accb714d64c7e0203ba120ca77f376a",
    "content_sha256": "eed21c095d54b9797228f795b48b446a8ee263357a8b412134cfe36ef94f2487",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "A las 38 semanas, un ponderado fetal en percentil 1 constituye restricción grave del crecimiento fetal. En este contexto, la gestación ya está a término y el perfil biofísico es 6/10, por lo que corresponde culminar la gestación en lugar de diferirla.",
    "why_not_a": "Esperar evolución espontánea prolonga una gestación con restricción grave y bienestar fetal no completamente tranquilizador.",
    "why_not_b": "Diferir hasta las 40 semanas no es apropiado en una restricción grave ya diagnosticada a las 38 semanas.",
    "why_not_c": "",
    "why_not_d": "Un control recién en una semana retrasa una conducta que ya está indicada por la edad gestacional y la severidad del crecimiento restringido.",
    "why_not_e": "",
    "exam_pearl": "RCIU/FGR grave: EFW <p3. A término, la conducta suele ser culminar; el Doppler ayuda a decidir el momento antes del término.",
    "update_alert": "",
    "reference_notes": "A las 38 semanas, un peso fetal estimado <p3 constituye restricción grave del crecimiento y ya tiene indicación de culminación; un perfil biofísico 6/10 refuerza la necesidad de no diferir la conducta.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "A las 38 semanas, un peso fetal estimado <p3 constituye restricción grave del crecimiento y ya tiene indicación de culminación; un perfil biofísico 6/10 refuerza la necesidad de no diferir la conducta.",
    "audit_current_answer": "C. Terminar la gestación",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://publications.smfm.org/publications/289-society-for-maternal-fetal-medicine-consult-series-52/",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-A-005",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "5",
    "area": "Salud Pública",
    "specialty": "Gestión sanitaria",
    "topic": "Dengue",
    "subtopic": "Acción intersectorial y determinantes",
    "question": "En el ámbito sanitario de una red integrada de servicio de salud (RISS), se presenta un brote de dengue con incremento diario de casos. ¿Qué estrategia debe priorizar el equipo de gestión para reducir la incidencia?",
    "option_a": "Implementar nuevo servicio de cuidados intensivos",
    "option_b": "Incrementar el requerimiento de medicamentos e insumos",
    "option_c": "Solicitar contrato de personal especializado",
    "option_d": "Acción intersectorial y abordaje de los determinantes",
    "option_e": "",
    "official_answer": "D",
    "official_answer_text": "Acción intersectorial y abordaje de los determinantes",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "55.20,442.85,540.10,455.45",
    "source_pdf": "2024 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "dc3bd5da40436c820a1ddf9046bf185b5accb714d64c7e0203ba120ca77f376a",
    "content_sha256": "d68b9bcc7dabc95a3d6f01c9f1f2c3b98d473bd72ab99565dd71cfe3b2dd0028",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "Si el objetivo es reducir la incidencia de dengue, debe actuarse sobre la transmisión y sus determinantes: control vectorial, ambiente, agua, residuos, participación comunitaria y coordinación intersectorial. Aumentar capacidad hospitalaria mejora la respuesta a los casos, pero no reduce por sí mismo la aparición de nuevos casos.",
    "why_not_a": "Una nueva UCI mejora capacidad para tratar dengue grave, pero es una intervención asistencial y no corta la transmisión.",
    "why_not_b": "Aumentar medicamentos e insumos prepara la atención de enfermos; no modifica directamente los determinantes que generan nuevos casos.",
    "why_not_c": "Contratar personal especializado puede ampliar la respuesta sanitaria, pero no es la estrategia poblacional principal para reducir incidencia.",
    "why_not_d": "",
    "why_not_e": "",
    "exam_pearl": "Incidencia de dengue ↓ = intervenir transmisión y determinantes; letalidad ↓ = mejorar diagnóstico y atención oportuna.",
    "update_alert": "",
    "reference_notes": "Para reducir incidencia de dengue, la intervención prioritaria debe actuar sobre transmisión y determinantes mediante coordinación intersectorial e intervención integrada, no solo ampliar capacidad asistencial para tratar casos.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "Para reducir incidencia de dengue, la intervención prioritaria debe actuar sobre transmisión y determinantes mediante coordinación intersectorial e intervención integrada, no solo ampliar capacidad asistencial para tratar casos.",
    "audit_current_answer": "D. Acción intersectorial y abordaje de los determinantes",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://iris.who.int/bitstreams/324aeff7-417c-4afe-8588-53b85b774ec2/download",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-B-001",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "1",
    "area": "Cirugía",
    "specialty": "Traumatología",
    "topic": "Bursitis de rodilla",
    "subtopic": "Bursitis prepatelar",
    "question": "Mujer de 45 años, que labora como operaria de limpieza, relata que los últimos cuatro días tuvo que refregar pisos en posición de rodillas ocasionándole dolor y aumento de volumen de la rodilla derecha que dificulta la deambulación y sus actividades habituales. ¿Cuál es la lesión anatómica más probable?",
    "option_a": "Rótula",
    "option_b": "Meniscos",
    "option_c": "Bursa de la rodilla",
    "option_d": "Ligamento cruzado",
    "option_e": "",
    "official_answer": "C",
    "official_answer_text": "Bursa de la rodilla",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.97,114.62,540.10,127.22",
    "source_pdf": "2024 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "d287aa82a3b73ec5c0945c08b6ac9cff30ed14e1f9160a2fd677f64d16b99066",
    "content_sha256": "7c25a01f3872792cedd5217172533dcc135d9661376ffb372a29fbdb25f0c73c",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "Arrodillarse repetidamente produce presión y microtrauma sobre la bursa prepatelar, causando bursitis prepatelar, clásicamente asociada a trabajos realizados de rodillas.",
    "why_not_a": "Una lesión de la rótula suele relacionarse con trauma directo importante y puede producir fractura, no este cuadro típico por sobreuso y presión repetida.",
    "why_not_b": "Las lesiones meniscales suelen asociarse a torsión, dolor en la interlínea, bloqueo o chasquidos, no a presión repetida anterior al arrodillarse.",
    "why_not_c": "",
    "why_not_d": "Una lesión del ligamento cruzado suele ocurrir por mecanismo de pivotaje o desaceleración y produce inestabilidad, no una tumefacción prepatelar por arrodillarse.",
    "why_not_e": "",
    "exam_pearl": "“Rodilla de la criada” / housemaid's knee = bursitis prepatelar por arrodillarse repetidamente.",
    "update_alert": "",
    "reference_notes": "La presión repetida al permanecer de rodillas se asocia clásicamente con bursitis prepatelar; entre las alternativas, la estructura lesionada es la bursa de la rodilla.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "La presión repetida al permanecer de rodillas se asocia clásicamente con bursitis prepatelar; entre las alternativas, la estructura lesionada es la bursa de la rodilla.",
    "audit_current_answer": "C. Bursa de la rodilla",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-B-002",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "2",
    "area": "Cirugía",
    "specialty": "Cirugía digestiva",
    "topic": "Complicaciones de pancreatitis",
    "subtopic": "Seudoquiste pancreático",
    "question": "Mujer de 70 años con diagnóstico de pancreatitis biliar grave hace un mes y medio, actualmente refiere dolor persistente en epigastrio, náusea y llenura precoz. Examen de abdomen: se palpa tumoración de 15x15 cm, poco movil y de bordes irregulares. ¿Cuál es el diagnóstico probable?",
    "option_a": "Neoplasia pancreática",
    "option_b": "Acumulación de líquido pancreático",
    "option_c": "Acumulación necrótica aguda",
    "option_d": "Seudoquiste pancreático",
    "option_e": "",
    "official_answer": "D",
    "official_answer_text": "Seudoquiste pancreático",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.97,202.94,540.10,215.66",
    "source_pdf": "2024 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "d287aa82a3b73ec5c0945c08b6ac9cff30ed14e1f9160a2fd677f64d16b99066",
    "content_sha256": "e10a9e6641c9ab20a4fe2b8d7f926365425f81eca5507f8c13f41cde5b8bf985",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA_CON_CAVEAT",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "La clave oficial es seudoquiste pancreático. Una colección que persiste más de 4 semanas después de pancreatitis y se vuelve organizada/encapsulada puede corresponder a seudoquiste si contiene esencialmente líquido y no necrosis. El tiempo de un mes y medio favorece una colección pancreática madura.",
    "why_not_a": "La relación temporal con una pancreatitis grave hace más probable una complicación local pospancreatitis que una neoplasia de nueva presentación.",
    "why_not_b": "La colección líquida pancreática aguda se usa para colecciones tempranas, típicamente dentro de las primeras 4 semanas y sin una pared bien definida.",
    "why_not_c": "La colección necrótica aguda también corresponde a una fase temprana, <4 semanas. Después de 4 semanas, si hay necrosis encapsulada, el término correcto es necrosis encapsulada (walled-off necrosis), que no aparece como alternativa.",
    "why_not_d": "",
    "why_not_e": "",
    "exam_pearl": "Atlanta revisada: <4 sem = colección aguda; >4 sem y encapsulada = seudoquiste si es líquida, necrosis encapsulada si contiene detritos necróticos.",
    "update_alert": "El enunciado no aporta imagen ni contenido de la colección; en pancreatitis necrotizante tardía debe considerarse necrosis encapsulada.",
    "reference_notes": "A las 6 semanas de una pancreatitis, una colección encapsulada sin necrosis corresponde a seudoquiste. Sin embargo, tras pancreatitis grave/necrotizante también puede existir necrosis encapsulada (walled-off necrosis), que requiere imagen para diferenciarse. La alternativa C 'acumulación necrótica aguda' no corresponde por el tiempo >4 semanas.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA_CON_CAVEAT",
    "audit_current_assessment": "A las 6 semanas de una pancreatitis, una colección encapsulada sin necrosis corresponde a seudoquiste. Sin embargo, tras pancreatitis grave/necrotizante también puede existir necrosis encapsulada (walled-off necrosis), que requiere imagen para diferenciarse. La alternativa C 'acumulación necrótica aguda' no corresponde por el tiempo >4 semanas.",
    "audit_current_answer": "D. Seudoquiste pancreático, si la colección es líquida y sin necrosis.",
    "audit_app_behavior": "Puntuar normalmente, pero mostrar caveat de nomenclatura de Atlanta después de responder.",
    "audit_source_urls": "https://gut.bmj.com/content/early/2012/10/24/gutjnl-2012-302779?versioned=true",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-B-003",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "3",
    "area": "Pediatría",
    "specialty": "Dermatología pediátrica",
    "topic": "Escabiosis",
    "subtopic": "Tratamiento tópico",
    "question": "Lactante de 10 meses, irritable, piel con lesiones papulares eritematosas en abdomen, axilas, codos y muslos, algunas costras en palmas y plantas. Madre presenta lesiones similares en abdomen. ¿Cuál es el tratamiento tópico de elección?",
    "option_a": "Tacrolimus",
    "option_b": "Lindano",
    "option_c": "Permetrina al 5%",
    "option_d": "Mometasona al 1%",
    "option_e": "",
    "official_answer": "C",
    "official_answer_text": "Permetrina al 5%",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.97,253.46,540.10,266.06",
    "source_pdf": "2024 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "d287aa82a3b73ec5c0945c08b6ac9cff30ed14e1f9160a2fd677f64d16b99066",
    "content_sha256": "8893883592c4c0a1291cf386ea04d15a6cb0abdcecb01ad57d86d6259ae62e80",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "El cuadro es compatible con escabiosis: prurito, distribución típica en lactante —incluidas palmas y plantas— y contacto domiciliario afectado. La permetrina al 5% es tratamiento tópico de primera línea y puede utilizarse en mayores de 2 meses.",
    "why_not_a": "Tacrolimus es un inmunomodulador usado en dermatitis atópica; no erradica Sarcoptes scabiei.",
    "why_not_b": "El lindano no es de primera línea por su potencial neurotoxicidad y debe evitarse especialmente en lactantes y niños pequeños.",
    "why_not_c": "",
    "why_not_d": "La mometasona puede disminuir inflamación y prurito, pero no elimina el ácaro y puede enmascarar el cuadro.",
    "why_not_e": "",
    "exam_pearl": "Escabiosis en lactantes puede comprometer palmas, plantas y cuero cabelludo. Tratar también contactos estrechos y medidas sobre ropa/ropa de cama.",
    "update_alert": "",
    "reference_notes": "La permetrina tópica al 5% es tratamiento de primera línea para escabiosis y puede usarse desde los 2 meses de edad; el lactante tiene 10 meses.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "La permetrina tópica al 5% es tratamiento de primera línea para escabiosis y puede usarse desde los 2 meses de edad; el lactante tiene 10 meses.",
    "audit_current_answer": "C. Permetrina al 5%",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://www.cdc.gov/scabies/hcp/clinical-care/index.html",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-B-004",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "4",
    "area": "Pediatría",
    "specialty": "Emergencias pediátricas",
    "topic": "Reanimación cardiopulmonar",
    "subtopic": "Relación compresión-ventilación",
    "question": "En la RCP básica de alta calidad del lactante y niño, se recomienda iniciar compresiones y ventilaciones ...... con un solo reanimador.",
    "option_a": "30/2",
    "option_b": "15/2",
    "option_c": "40/1",
    "option_d": "40/2",
    "option_e": "",
    "official_answer": "A",
    "official_answer_text": "30/2",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "55.20,316.61,281.33,329.21",
    "source_pdf": "2024 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "d287aa82a3b73ec5c0945c08b6ac9cff30ed14e1f9160a2fd677f64d16b99066",
    "content_sha256": "59c634f69298b9f9af1f02f399abf30b34216ed37ee732bf180130614a4332ed",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "En RCP pediátrica sin vía aérea avanzada, un solo reanimador utiliza 30 compresiones por 2 ventilaciones. Cuando hay dos reanimadores en un niño prepúber, la relación cambia a 15:2.",
    "why_not_a": "",
    "why_not_b": "15:2 corresponde al esquema de dos reanimadores en lactantes y niños prepúberes, no a un solo reanimador.",
    "why_not_c": "40:1 no es una relación recomendada de RCP pediátrica.",
    "why_not_d": "40:2 no es una relación recomendada de RCP pediátrica.",
    "why_not_e": "",
    "exam_pearl": "Pediatría: 1 reanimador = 30:2; 2 reanimadores = 15:2 en prepuberales.",
    "update_alert": "",
    "reference_notes": "En lactantes y niños con un solo reanimador, la relación compresión:ventilación es 30:2; 15:2 corresponde a dos reanimadores.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "En lactantes y niños con un solo reanimador, la relación compresión:ventilación es 30:2; 15:2 corresponde a dos reanimadores.",
    "audit_current_answer": "A. 30/2",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://www.ahajournals.org/doi/10.1161/CIR.0000000000000901",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2024-B-005",
    "year": "2024",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "5",
    "area": "Pediatría",
    "specialty": "Neonatología",
    "topic": "Ictericia neonatal",
    "subtopic": "Fallo de la lactancia",
    "question": "Neonato de 5 días, es traído por madre quien refiere notarlo muy amarillo. Nacido de parto eutócico, peso al nacer: 3500 g, adecuado para la edad gestacional; luego de alta conjunta, recibe lactancia materna exclusiva. Peso actual 3200 g, ictericia hasta raíz de muslos, presencia de reflejo de búsqueda y succión. ¿Cuál es la causa más probable de la ictericia?",
    "option_a": "Incompatibilidad Rh",
    "option_b": "Fallo de la lactancia",
    "option_c": "Hepatitis del RN",
    "option_d": "Cefalohematoma",
    "option_e": "",
    "official_answer": "B",
    "official_answer_text": "Fallo de la lactancia",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "55.20,404.93,281.33,417.65",
    "source_pdf": "2024 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "d287aa82a3b73ec5c0945c08b6ac9cff30ed14e1f9160a2fd677f64d16b99066",
    "content_sha256": "0fcdaaa6b950d337998fc339d653ab406a2796b11fc9ecc0883917c7bba05b01",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "A los 5 días, el neonato ha perdido 300 g de 3500 g, aproximadamente 8,6% del peso de nacimiento. En un lactante con lactancia exclusiva, esto sugiere ingesta insuficiente y aumento de la circulación enterohepática de bilirrubina: la denominada ictericia por ingesta subóptima, históricamente llamada “fallo de la lactancia”.",
    "why_not_a": "La enfermedad hemolítica por incompatibilidad Rh suele producir ictericia precoz, con frecuencia dentro de las primeras 24 horas, y puede acompañarse de anemia.",
    "why_not_b": "",
    "why_not_c": "La hepatitis neonatal suele producir hiperbilirrubinemia conjugada/colestasis y otros datos de enfermedad, no este patrón típico de ingesta subóptima.",
    "why_not_d": "Un cefalohematoma aumentaría la carga de bilirrubina, pero el enunciado no describe una colección hemática en el cuero cabelludo.",
    "why_not_e": "",
    "exam_pearl": "Día 3-5 + pérdida ponderal excesiva + lactancia ineficaz = ictericia por ingesta subóptima. Diferenciar de ictericia por leche materna más tardía.",
    "update_alert": "Terminología actual preferible: ictericia por ingesta subóptima (suboptimal intake jaundice).",
    "reference_notes": "Ictericia al día 5 en lactancia materna exclusiva con pérdida ponderal de 300 g/3500 g (≈8,6%) orienta a hiperbilirrubinemia por ingesta subóptima/fallo de la lactancia más que a hemólisis, hepatitis o cefalohematoma.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "Ictericia al día 5 en lactancia materna exclusiva con pérdida ponderal de 300 g/3500 g (≈8,6%) orienta a hiperbilirrubinemia por ingesta subóptima/fallo de la lactancia más que a hemólisis, hepatitis o cefalohematoma.",
    "audit_current_answer": "B. Fallo de la lactancia",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://publications.aap.org/pediatrics/article/150/1/e2022057988/188347/Policy-Statement-Breastfeeding-and-the-Use-of",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-A-001",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "1",
    "area": "Medicina Interna",
    "specialty": "Cardiología",
    "topic": "Emergencia hipertensiva",
    "subtopic": "Tratamiento inicial",
    "question": "Varón de 65 años con antecedente de hipertensión arterial, acude por cefalea intensa, convulsiones y edema de papila. Examen: PA: 190/120 mmHg. ¿Cuál es el medicamento inicial a usar?",
    "option_a": "Labetalol",
    "option_b": "Hidralazina",
    "option_c": "Nitroprusiato",
    "option_d": "Nitroglicerina",
    "option_e": "",
    "official_answer": "C",
    "official_answer_text": "Nitroprusiato",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.92,102.00,540.00,114.60",
    "source_pdf": "2025 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "cc4fe7436f2a408360bc265d87e287971212b37e169c1a17b134bc4e596540ce",
    "content_sha256": "824df1efb0109f937a4e47de1877999960a8534d603895f2fe62e913506262be",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "OBSERVADA_AMBIGUA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "Clave oficial CONAREME: C, nitroprusiato. El paciente tiene una emergencia hipertensiva con daño neurológico agudo compatible con encefalopatía hipertensiva; el nitroprusiato es un vasodilatador IV potente y titulable que históricamente se ha utilizado para reducir rápidamente la presión arterial. La pregunta queda marcada como ambigua porque labetalol también es una opción IV defendible y frecuentemente preferida en protocolos actuales.",
    "why_not_a": "Labetalol NO es claramente incorrecto: es un antihipertensivo IV ampliamente utilizado en emergencias hipertensivas. Su presencia como alternativa hace que la pregunta no tenga una única respuesta indiscutible según guías contemporáneas.",
    "why_not_b": "La hidralazina tiene una respuesta menos predecible y no suele ser la primera elección general para encefalopatía hipertensiva; tiene usos particulares, como ciertos contextos obstétricos.",
    "why_not_c": "",
    "why_not_d": "La nitroglicerina es especialmente útil cuando predomina isquemia miocárdica o edema agudo de pulmón; no es la opción general preferida para encefalopatía hipertensiva.",
    "why_not_e": "",
    "exam_pearl": "Emergencia hipertensiva = PA severamente elevada + daño agudo de órgano blanco. Usar fármaco IV titulable; la elección depende del órgano afectado.",
    "update_alert": "Pregunta con más de una opción IV defendible según guías/protocolos contemporáneos.",
    "reference_notes": "El cuadro es una emergencia hipertensiva con encefalopatía. El nitroprusiato es un antihipertensivo IV utilizable, pero no es una respuesta única: labetalol también es un agente recomendado y suele preferirse en muchos protocolos neurológicos por su perfil y titulación. Por ello, con A y C disponibles, la pregunta no tiene una única alternativa indiscutible según guías actuales.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "OBSERVADA_AMBIGUA",
    "audit_current_assessment": "El cuadro es una emergencia hipertensiva con encefalopatía. El nitroprusiato es un antihipertensivo IV utilizable, pero no es una respuesta única: labetalol también es un agente recomendado y suele preferirse en muchos protocolos neurológicos por su perfil y titulación. Por ello, con A y C disponibles, la pregunta no tiene una única alternativa indiscutible según guías actuales.",
    "audit_current_answer": "No única: A (labetalol) y C (nitroprusiato) pueden ser defendibles según protocolo; labetalol suele ser preferido.",
    "audit_app_behavior": "Conservar C como clave oficial; marcar como ambigua y excluir del puntaje de dominio por defecto.",
    "audit_source_urls": "https://www.ahajournals.org/doi/10.1161/HYP.0000000000000238",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-A-002",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "2",
    "area": "Gineco-Obstetricia",
    "specialty": "Patología mamaria",
    "topic": "Galactorrea",
    "subtopic": "Evaluación inicial",
    "question": "Mujer de 32 años asintomática que acude por chequeo. Al examen de mama a la expresión de uno de los pezones sale secreción blanco lechoso. ¿Cuál es el manejo más adecuado?",
    "option_a": "Solicitar prolactina",
    "option_b": "Mamografía",
    "option_c": "Ecografía de mamas",
    "option_d": "Observación",
    "option_e": "",
    "official_answer": "D",
    "official_answer_text": "Observación",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.92,177.72,540.00,190.32",
    "source_pdf": "2025 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "cc4fe7436f2a408360bc265d87e287971212b37e169c1a17b134bc4e596540ce",
    "content_sha256": "f8588b8d16eb63f86c2b4706b549adcd7174e9bdb71975b4eefe0c4fa025b032",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA_CON_CAVEAT",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "La secreción es blanca, aparece solo al expresar el pezón y la paciente está asintomática. Una secreción provocada y de aspecto fisiológico puede manejarse inicialmente con observación y evitando la estimulación repetida. La pregunta tiene un caveat: la unilateralidad exige vigilar que no se vuelva espontánea, persistente o uniductal.",
    "why_not_a": "La prolactina se solicita cuando hay verdadera galactorrea persistente o espontánea y/o datos endocrinos como alteraciones menstruales, infertilidad o síntomas de hiperprolactinemia. En una secreción solo provocada y asintomática, no es necesariamente el primer paso.",
    "why_not_b": "La mamografía no es el primer estudio de una secreción fisiológica provocada en una mujer asintomática; se reserva la imagen para secreción patológica según edad y características.",
    "why_not_c": "La ecografía tampoco es obligatoria en una secreción claramente fisiológica; sí se indica si la secreción es patológica o aparece una masa/otro hallazgo.",
    "why_not_d": "",
    "why_not_e": "",
    "exam_pearl": "Secreción patológica: espontánea, unilateral/uniductal, sanguinolenta o serosa. Secreción fisiológica: suele ser provocada y no requiere imagen rutinaria.",
    "update_alert": "La unilateralidad hace el enunciado menos limpio; vigilar características de secreción patológica.",
    "reference_notes": "Una secreción lechosa únicamente provocada por expresión, sin síntomas ni masa, puede manejarse con observación y evitar estimulación repetida. No obstante, la unilateralidad es atípica para la secreción fisiológica clásica; si se vuelve espontánea, persistente o de un solo conducto, requiere evaluación dirigida. Si se trata de verdadera galactorrea, debe considerarse prolactina.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA_CON_CAVEAT",
    "audit_current_assessment": "Una secreción lechosa únicamente provocada por expresión, sin síntomas ni masa, puede manejarse con observación y evitar estimulación repetida. No obstante, la unilateralidad es atípica para la secreción fisiológica clásica; si se vuelve espontánea, persistente o de un solo conducto, requiere evaluación dirigida. Si se trata de verdadera galactorrea, debe considerarse prolactina.",
    "audit_current_answer": "D. Observación, aceptable por ser provocada y asintomática.",
    "audit_app_behavior": "Puntuar normalmente, mostrando caveat sobre unilateralidad y criterios de secreción patológica.",
    "audit_source_urls": "https://acsearch.acr.org/docs/3099312/Narrative/",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-A-003",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "3",
    "area": "Ciencias Básicas",
    "specialty": "Embriología",
    "topic": "Implantación",
    "subtopic": "Sitio de implantación",
    "question": "¿Cuál es el sitio más frecuente de implantación del blastocisto?",
    "option_a": "Fondo uterino",
    "option_b": "Segmento inferior del útero",
    "option_c": "Cérvix uterino",
    "option_d": "Cuerno uterino",
    "option_e": "",
    "official_answer": "A",
    "official_answer_text": "Fondo uterino",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "55.20,215.64,281.28,228.24",
    "source_pdf": "2025 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "cc4fe7436f2a408360bc265d87e287971212b37e169c1a17b134bc4e596540ce",
    "content_sha256": "c0aba502f0460fcc0b5991187c8eee8bb1d354a79b51dc92cd1431f37f35526d",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "La implantación normal ocurre con mayor frecuencia en el endometrio de la porción superior del cuerpo uterino, habitualmente cerca del fondo y con frecuencia en la pared posterior.",
    "why_not_a": "",
    "why_not_b": "La implantación en el segmento uterino inferior se asocia a placentación baja/placenta previa, no al sitio más frecuente normal.",
    "why_not_c": "La implantación cervical es ectópica y potencialmente hemorrágica.",
    "why_not_d": "La implantación en el cuerno uterino corresponde a una localización anormal/intersticial o cornual según el contexto.",
    "why_not_e": "",
    "exam_pearl": "Implantación normal: endometrio del cuerpo uterino alto, típicamente pared posterior cerca del fondo.",
    "update_alert": "",
    "reference_notes": "La implantación normal ocurre con mayor frecuencia en el endometrio de la porción superior del cuerpo uterino, habitualmente en la pared posterior cercana al fondo; 'fondo uterino' es la mejor alternativa disponible.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "La implantación normal ocurre con mayor frecuencia en el endometrio de la porción superior del cuerpo uterino, habitualmente en la pared posterior cercana al fondo; 'fondo uterino' es la mejor alternativa disponible.",
    "audit_current_answer": "A. Fondo uterino",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-A-004",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "4",
    "area": "Cirugía",
    "specialty": "Trauma",
    "topic": "Tórax inestable",
    "subtopic": "Manejo inicial",
    "question": "Varón de 43 años, llevado a urgencias porque sufrió hace 30 minutos impacto de timón en el tórax por accidente de tránsito. Presenta disnea intensa, dolor torácico izquierdo, taquipnea. Examen: PA:80/40 mmHg, FC: 100X', FR: 36X'; cianosis distal, movimiento paradojal de la pared torácica. RX: múltiples fracturas costales izquierdas. ¿Cuál es la conducta más adecuada?",
    "option_a": "Colocación de catéter central",
    "option_b": "Ventilación no invasiva",
    "option_c": "Fijación costal quirúrgica",
    "option_d": "Intubación orotraqueal",
    "option_e": "",
    "official_answer": "D",
    "official_answer_text": "Intubación orotraqueal",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.92,316.56,540.00,329.16",
    "source_pdf": "2025 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "cc4fe7436f2a408360bc265d87e287971212b37e169c1a17b134bc4e596540ce",
    "content_sha256": "9075399ea2420a40e8dabef90808d63c310c171ba9c1222c5f75ad6e9514d6a2",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "El paciente presenta tórax inestable con insuficiencia respiratoria e inestabilidad hemodinámica: disnea intensa, FR 36, cianosis y PA 80/40 mmHg. La prioridad es asegurar la vía aérea y ventilación mediante intubación orotraqueal. La indicación no es el movimiento paradójico aislado, sino el fracaso fisiológico.",
    "why_not_a": "Un catéter venoso central puede ser útil para manejo hemodinámico, pero no resuelve la amenaza inmediata de ventilación y oxigenación.",
    "why_not_b": "La ventilación no invasiva puede considerarse en pacientes seleccionados y estables; este paciente está en shock y con compromiso respiratorio grave.",
    "why_not_c": "La fijación quirúrgica costal puede ser útil en casos seleccionados, pero no precede a la estabilización inicial de vía aérea, respiración y circulación.",
    "why_not_d": "",
    "why_not_e": "",
    "exam_pearl": "Tórax inestable: no todo paciente requiere intubación. Intubar si hay insuficiencia respiratoria, hipoxemia, fatiga o inestabilidad que impida ventilación segura.",
    "update_alert": "Perla: no intubar solo por el movimiento paradójico; la indicación aquí es el fracaso respiratorio y la inestabilidad.",
    "reference_notes": "El tórax inestable por sí solo no obliga a intubar, pero este paciente presenta disnea intensa, FR 36, cianosis, hipoxemia clínica y shock; hay insuficiencia respiratoria/compromiso fisiológico que justifica control definitivo de la vía aérea y ventilación invasiva.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "El tórax inestable por sí solo no obliga a intubar, pero este paciente presenta disnea intensa, FR 36, cianosis, hipoxemia clínica y shock; hay insuficiencia respiratoria/compromiso fisiológico que justifica control definitivo de la vía aérea y ventilación invasiva.",
    "audit_current_answer": "D. Intubación orotraqueal",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://www.east.org/education-resources/practice-management-guidelines/details/pulmonary-contusion-and-flail-chest%2C-management-of",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-A-005",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "A",
    "question_number": "5",
    "area": "Medicina Interna",
    "specialty": "Neurología",
    "topic": "Pares craneales",
    "subtopic": "III par craneal",
    "question": "Varón de 27 años, acude a consulta por visión doble y caída del párpado derecho. Examen: se evidencia pupila derecha dilatada con incapacidad para mover el ojo hacia el lado nasal ¿Cuál es el par craneal comprometido?",
    "option_a": "VI",
    "option_b": "I",
    "option_c": "III",
    "option_d": "IV",
    "option_e": "",
    "official_answer": "C",
    "official_answer_text": "III",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.92,367.08,540.00,379.68",
    "source_pdf": "2025 ESPECIALIADAD A.pdf",
    "source_page": "1",
    "source_sha256": "cc4fe7436f2a408360bc265d87e287971212b37e169c1a17b134bc4e596540ce",
    "content_sha256": "f73986f9ddc2f92e12fae1938d7505a8c8ac7f64e5292d3ba16b1f683563d302",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "El III par craneal (oculomotor) inerva el elevador del párpado, la mayoría de músculos extraoculares y lleva fibras parasimpáticas pupilares. Su lesión puede producir ptosis, midriasis y limitación de la aducción, como en este caso.",
    "why_not_a": "El VI par inerva el recto lateral; su lesión produce incapacidad para abducir el ojo, no midriasis ni ptosis.",
    "why_not_b": "El I par es el nervio olfatorio y no controla movimientos oculares ni la pupila.",
    "why_not_c": "",
    "why_not_d": "El IV par inerva el oblicuo superior; su lesión causa diplopía vertical, sobre todo al mirar abajo y adentro, sin midriasis típica.",
    "why_not_e": "",
    "exam_pearl": "III par: ojo “abajo y afuera” + ptosis; compromiso parasimpático = midriasis. Pupila dilatada dolorosa obliga a pensar en lesión compresiva.",
    "update_alert": "",
    "reference_notes": "Ptosis, midriasis y déficit de aducción ocular son compatibles con lesión del III par craneal (oculomotor).",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "Ptosis, midriasis y déficit de aducción ocular son compatibles con lesión del III par craneal (oculomotor).",
    "audit_current_answer": "C. III",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-B-001",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "1",
    "area": "Cirugía",
    "specialty": "Trauma",
    "topic": "Lesión traqueobronquial",
    "subtopic": "Trauma torácico penetrante",
    "question": "Varón de 21 años, es trasladado por haber sufrido asalto con arma de fuego, ingresa con disnea y hemoptisis. Examen: PA: 90/50 mmHg, FR: 30X', FC: 100X', SatO2: 90%; orificio de entrada a nivel de HTD tercio medio cara anterior, enfisema subcutáneo, MV abolido en HTD. ¿Cuál es la estructura anatómica afectada?",
    "option_a": "Vena cava superior",
    "option_b": "Diafragma",
    "option_c": "Árbol traqueobronquial",
    "option_d": "Arteria torácica interna",
    "option_e": "",
    "official_answer": "C",
    "official_answer_text": "Árbol traqueobronquial",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.92,114.60,540.00,127.20",
    "source_pdf": "2025 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "535d1af9512f43227302228006f654a2f5e021e2b4c283313aca5de39bb7861c",
    "content_sha256": "21a64716b1c0b39f1437b8231db2ce2591f8ce5dde59e8da6fa5c64017092ef1",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "Disnea, hemoptisis y enfisema subcutáneo tras trauma penetrante sugieren una lesión con fuga de aire y sangrado desde la vía aérea. Entre las alternativas, el árbol traqueobronquial es la estructura que mejor integra estos hallazgos.",
    "why_not_a": "Una lesión de la vena cava superior produciría principalmente hemorragia masiva y compromiso hemodinámico; no explica bien el enfisema subcutáneo y la hemoptisis.",
    "why_not_b": "Una lesión diafragmática suele asociarse a trayectos toracoabdominales y herniación de vísceras; no es la mejor explicación para hemoptisis y fuga aérea.",
    "why_not_c": "",
    "why_not_d": "La arteria torácica interna puede causar hemorragia/hemotórax, pero no explica de forma primaria la hemoptisis y el enfisema subcutáneo.",
    "why_not_e": "",
    "exam_pearl": "Trauma + enfisema subcutáneo importante + fuga aérea/hemoptisis = sospechar lesión traqueobronquial.",
    "update_alert": "",
    "reference_notes": "Tras trauma torácico penetrante, la combinación de hemoptisis, enfisema subcutáneo, disnea e importante alteración ventilatoria hace sospechar lesión del árbol traqueobronquial; es la mejor opción ofrecida.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "Tras trauma torácico penetrante, la combinación de hemoptisis, enfisema subcutáneo, disnea e importante alteración ventilatoria hace sospechar lesión del árbol traqueobronquial; es la mejor opción ofrecida.",
    "audit_current_answer": "C. Árbol traqueobronquial",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-B-002",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "2",
    "area": "Pediatría",
    "specialty": "Genética clínica",
    "topic": "Síndrome de Down",
    "subtopic": "Reconocimiento fenotípico",
    "question": "RN producto de parto eutócico, EG 38 semanas, APGAR 8-9. Examen: cara: puente nasal aplanado, ojos almendrados con pliegue epicántico, orejas pequeñas. Línea única en la palma de la mano, flacidez y reflejo de succión alterado. ¿Cuál es el síndrome?",
    "option_a": "Crouzon",
    "option_b": "Apert",
    "option_c": "Treacher Collins",
    "option_d": "Down",
    "option_e": "",
    "official_answer": "D",
    "official_answer_text": "Down",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.92,202.92,540.00,215.64",
    "source_pdf": "2025 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "535d1af9512f43227302228006f654a2f5e021e2b4c283313aca5de39bb7861c",
    "content_sha256": "4a48a4f4dc1c9f6587ea1c5d60c6d22f9457430fd719841e57f27b3063f99f7c",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "La combinación de hipotonía neonatal, puente nasal aplanado, pliegues epicánticos, orejas pequeñas y pliegue palmar único es típica de síndrome de Down, debido en la mayoría de casos a trisomía 21.",
    "why_not_a": "Crouzon es una craneosinostosis con alteraciones craneofaciales y proptosis; no explica el fenotipo sistémico descrito.",
    "why_not_b": "Apert combina craneosinostosis con sindactilia marcada de manos y pies, hallazgo no descrito.",
    "why_not_c": "Treacher Collins produce hipoplasia malar/mandibular y anomalías auriculares, sin el patrón típico de hipotonía y pliegue palmar único de trisomía 21.",
    "why_not_d": "",
    "why_not_e": "",
    "exam_pearl": "Down: hipotonía + epicanto + puente nasal plano + pliegue palmar único; confirmar con estudio citogenético.",
    "update_alert": "",
    "reference_notes": "Hipotonía neonatal, puente nasal aplanado, epicanto, orejas pequeñas y pliegue palmar único son hallazgos fenotípicos clásicos compatibles con síndrome de Down.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "Hipotonía neonatal, puente nasal aplanado, epicanto, orejas pequeñas y pliegue palmar único son hallazgos fenotípicos clásicos compatibles con síndrome de Down.",
    "audit_current_answer": "D. Down",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-B-003",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "3",
    "area": "Medicina Interna",
    "specialty": "Nefrología",
    "topic": "Peritonitis asociada a diálisis peritoneal",
    "subtopic": "Tratamiento",
    "question": "Mujer de 48 años en diálisis peritoneal desde hace 2 años, presenta fiebre, náusea, dolor y distensión abdominal. Examen: PA: 110/70 mmHg, T°: 38.6 °C; abdomen: RHA presentes, blando, depresible, en catéter de diálisis se evidencia líquido turbio. Laboratorio: recuento celular en líquido peritoneal de 520/µL; PMN: 90%. ¿Cuál es el tratamiento de elección?",
    "option_a": "Gentamicina + vancomicina",
    "option_b": "Vancomicina",
    "option_c": "Ceftriaxona",
    "option_d": "Ceftriaxona + gentamicina",
    "option_e": "",
    "official_answer": "A",
    "official_answer_text": "Gentamicina + vancomicina",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "55.20,266.04,281.28,278.76",
    "source_pdf": "2025 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "535d1af9512f43227302228006f654a2f5e021e2b4c283313aca5de39bb7861c",
    "content_sha256": "0da63043d552278fc45661ae83fe05c054a56745f55b9695a20dd3be9e7fabf1",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA_CON_CAVEAT",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "La paciente cumple criterios de peritonitis asociada a diálisis peritoneal: clínica compatible, efluente turbio y >100 leucocitos/µL con >50% PMN. El tratamiento empírico debe cubrir grampositivos y gramnegativos. Vancomicina + gentamicina es una combinación aceptable entre las alternativas. La vía intraperitoneal suele ser preferida si es factible y no hay sepsis sistémica.",
    "why_not_a": "",
    "why_not_b": "Vancomicina sola cubre principalmente grampositivos y deja sin cobertura empírica adecuada a los gramnegativos.",
    "why_not_c": "Ceftriaxona sola no proporciona la cobertura empírica recomendada para todo el espectro, especialmente grampositivos resistentes según epidemiología local.",
    "why_not_d": "Ceftriaxona + gentamicina concentra la cobertura en gramnegativos y no ofrece la cobertura grampositiva empírica que aporta vancomicina o una cefalosporina de primera generación.",
    "why_not_e": "",
    "exam_pearl": "Peritonitis en diálisis peritoneal: dolor/efluente turbio + WBC >100/µL y PMN >50%. Empírico = cubrir gram+ y gram−; adaptar al antibiograma local.",
    "update_alert": "No es un régimen universal único; el esquema empírico depende de sensibilidad local y debe cubrir grampositivos y gramnegativos.",
    "reference_notes": "El cuadro cumple criterios de peritonitis asociada a diálisis peritoneal. La terapia empírica debe cubrir grampositivos y gramnegativos; vancomicina + un aminoglucósido como gentamicina es un esquema aceptable según susceptibilidad local. La vía intraperitoneal es la preferida cuando es posible y no existe un único esquema universal de 'elección'.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA_CON_CAVEAT",
    "audit_current_assessment": "El cuadro cumple criterios de peritonitis asociada a diálisis peritoneal. La terapia empírica debe cubrir grampositivos y gramnegativos; vancomicina + un aminoglucósido como gentamicina es un esquema aceptable según susceptibilidad local. La vía intraperitoneal es la preferida cuando es posible y no existe un único esquema universal de 'elección'.",
    "audit_current_answer": "A. Gentamicina + vancomicina, como esquema empírico aceptable.",
    "audit_app_behavior": "Puntuar normalmente, mostrando caveat de vía intraperitoneal y adaptación a epidemiología local.",
    "audit_source_urls": "https://ispd.org/wp-content/uploads/2025/09/LI-ET-1.pdf",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-B-004",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "4",
    "area": "Medicina Interna",
    "specialty": "Patología vascular",
    "topic": "Tromboangeítis obliterante",
    "subtopic": "Histopatología",
    "question": "Varón de 35 años, fumador desde los 14 años, presenta frialdad distal asimétrica de extremidades. Examen: pulsos periféricos disminuidos en mano derecha; prueba de Allen (+), presencia de úlcera isquémica en 2° dedo de pie izquierdo. ¿Cuál es la morfología en la anatomía patológica?",
    "option_a": "Engrosamiento de la íntima con placas ateromatosas y trombos superpuestos a placas ulceradas",
    "option_b": "Vasos con inflamación, obstruidos por trombos intraluminales con microabscesos compuestos por neutrófilos",
    "option_c": "Células inflamatorias dispersas, con calcificación y neovascularización con ulceraciones múltiples",
    "option_d": "Vasos con densos cúmulos de células atípicas que revisten la luz vascular, ocluyéndola totalmente",
    "option_e": "",
    "official_answer": "B",
    "official_answer_text": "Vasos con inflamación, obstruidos por trombos intraluminales con microabscesos compuestos por neutrófilos",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "55.20,354.48,540.00,367.08",
    "source_pdf": "2025 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "535d1af9512f43227302228006f654a2f5e021e2b4c283313aca5de39bb7861c",
    "content_sha256": "fdac3b7aca9f884cedeb29abd21882e754a5232d09d30797577216aac638dc4c",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "El cuadro clínico corresponde a tromboangeítis obliterante (enfermedad de Buerger) en un fumador joven con isquemia distal. Histológicamente, en la fase aguda hay trombos inflamatorios oclusivos con microabscesos formados por neutrófilos, con relativa preservación de la pared vascular.",
    "why_not_a": "Describe aterosclerosis: placas ateromatosas de la íntima con trombosis sobre placas complicadas, más típica de enfermedad arterial aterosclerótica.",
    "why_not_b": "",
    "why_not_c": "La calcificación y neovascularización no describen la lesión histológica clásica de la tromboangeítis obliterante.",
    "why_not_d": "Cúmulos de células atípicas que revisten y ocluyen vasos sugieren una neoplasia vascular, no una vasculopatía inflamatoria trombótica.",
    "why_not_e": "",
    "exam_pearl": "Buerger = fumador joven + isquemia distal + trombosis inflamatoria segmentaria con microabscesos neutrofílicos. Tratamiento clave: abandono total del tabaco.",
    "update_alert": "",
    "reference_notes": "La tromboangeítis obliterante se caracteriza en fase aguda por oclusión trombótica inflamatoria con microabscesos ricos en neutrófilos, con relativa preservación de la pared vascular.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "La tromboangeítis obliterante se caracteriza en fase aguda por oclusión trombótica inflamatoria con microabscesos ricos en neutrófilos, con relativa preservación de la pared vascular.",
    "audit_current_answer": "B. Vasos con inflamación y trombos intraluminales con microabscesos de neutrófilos",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://www.ahajournals.org/doi/pdf/10.1161/circulationaha.114.009935",
    "audit_date": "2026-07-14"
  },
  {
    "id": "RM-2025-B-005",
    "year": "2025",
    "exam": "Residentado Médico Perú",
    "test": "B",
    "question_number": "5",
    "area": "Gineco-Obstetricia",
    "specialty": "Uroginecología",
    "topic": "Prolapso de órganos pélvicos",
    "subtopic": "Clasificación POP-Q",
    "question": "Mujer de 75 años, acude por sensación de bulto en zona vaginal. No refiere escape de orina. Examen: POPQ: Aa 0, Ba +1; longitud total de la vagina 7 cm. ¿Cuál es el grado del prolapso?",
    "option_a": "IV",
    "option_b": "I",
    "option_c": "II",
    "option_d": "III",
    "option_e": "",
    "official_answer": "C",
    "official_answer_text": "II",
    "key_detection_method": "Rectángulo vectorial amarillo superpuesto a la alternativa en el PDF original",
    "key_verification_status": "VERIFICADA_PDF_VECTOR",
    "key_visual_fill": "#FFF215 aprox.",
    "key_visual_bbox": "313.92,430.20,540.00,442.80",
    "source_pdf": "2025 ESPECIALIADAD B.pdf",
    "source_page": "1",
    "source_sha256": "535d1af9512f43227302228006f654a2f5e021e2b4c283313aca5de39bb7861c",
    "content_sha256": "bdb20f24c1c7b43a09463d924f48ea5ed449f9101c24f95cb90fd040ccab1480",
    "traceability_complete": "True",
    "extraction_status": "ESTRUCTURA_REVISADA",
    "medical_review_status": "VALIDADA",
    "explanation_status": "COMPLETA_REVISADA",
    "correct_explanation": "En POP-Q, el estadio II se define cuando el punto más distal del prolapso se encuentra entre 1 cm por encima y 1 cm por debajo del himen. Ba = +1 cm cae exactamente dentro del estadio II.",
    "why_not_a": "El estadio IV corresponde a eversión vaginal prácticamente completa, mucho más allá de los valores descritos.",
    "why_not_b": "El estadio I requiere que el borde más distal permanezca más de 1 cm por encima del himen.",
    "why_not_c": "",
    "why_not_d": "El estadio III requiere que el borde más distal protruda más de 1 cm por debajo del himen, sin llegar a la eversión completa; +1 cm todavía es estadio II.",
    "why_not_e": "",
    "exam_pearl": "POP-Q: II = −1 a +1 cm respecto al himen; III = >+1 cm pero no eversión completa; IV = eversión casi/completamente total.",
    "update_alert": "",
    "reference_notes": "En POP-Q, estadio II corresponde a un borde más distal entre −1 y +1 cm respecto del himen. Ba = +1 cm cae exactamente en estadio II; estadio III requiere >+1 cm.",
    "record_version": "0.3",
    "import_batch": "PILOTO-2026-07-14",
    "active": "True",
    "audit_status": "VALIDADA",
    "audit_current_assessment": "En POP-Q, estadio II corresponde a un borde más distal entre −1 y +1 cm respecto del himen. Ba = +1 cm cae exactamente en estadio II; estadio III requiere >+1 cm.",
    "audit_current_answer": "C. II",
    "audit_app_behavior": "Puntuar normalmente.",
    "audit_source_urls": "https://www.ics.org/Wasabi/Documents/DocumentsDownload.aspx?DocumentID=2015",
    "audit_date": "2026-07-14"
  }
];
